# PyInstaller spec for AppSleuth backend
# Produces a single standalone executable with all Python deps bundled

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('analyzers', 'analyzers'),
        ('ai', 'ai'),
        ('network', 'network'),
        ('memory', 'memory'),
    ],
    hiddenimports=[
        # uvicorn internals
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # fastapi / starlette
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.routing',
        'starlette.websockets',
        # async
        'anyio',
        'anyio._backends._asyncio',
        'anyio._backends._trio',
        'asyncio',
        # http
        'httpx',
        'h11',
        'httpcore',
        # data / serialization
        'pydantic',
        'pydantic.v1',
        'email.mime.multipart',
        'email.mime.text',
        'multipart',
        'python_multipart',
        # crypto
        'cryptography',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.backends',
        'cryptography.x509',
        'OpenSSL',
        # analysis
        'pefile',
        'jinja2',
        'anthropic',
        'httpx._transports.default',
        # standard
        'json',
        'gzip',
        'zlib',
        'ssl',
        'socket',
        'threading',
        'asyncio',
        'uuid',
        'tempfile',
        'zipfile',
        'hashlib',
        're',
        'os',
        'sys',
        'pathlib',
        'typing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'PIL',
        'PyQt5',
        'PyQt6',
        'wx',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='appsleuth-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
